# Generated by Django 5.0 on 2024-01-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirapp', '0002_userprofile_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pimage',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
